version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: t3-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./_offline:/var/tmp
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: t3